services:
  beedee:
    build:
      context: https://github.com/Oasis256/BeeDee.git
      dockerfile: Dockerfile.linux
      args:
        VITE_API_URL: /api
    image: beedee/bee-gateway:prod
    container_name: BeeGateway
    hostname: bee-gateway
    environment:
      - PORT=80
      - PROFILES_URL=http://bee-profiles:8080
      - RESULTS_URL=http://bee-results:8080
      - COMMS_URL=http://bee-comms:8080
      - EXPLORATION_URL=http://bee-exploration:8080
      - SAFETY_URL=http://bee-safety:8080
      - NOTIFY_URL=http://bee-notify:8080
    networks:
      default: {}
      macNet:
        ipv4_address: 10.0.0.31
    depends_on: [bee-profiles, bee-results, bee-comms, bee-exploration, bee-safety, bee-notify]

  bee-profiles:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/profiles-svc
      dockerfile: Dockerfile
    image: beedee/bee-profiles:prod
    container_name: BeeProfiles
    hostname: bee-profiles
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/profiles.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [profiles_data:/data]
    networks: [default]

  bee-results:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/results-svc
      dockerfile: Dockerfile
    image: beedee/bee-results:prod
    container_name: BeeResults
    hostname: bee-results
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/results.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [results_data:/data]
    networks: [default]

  bee-comms:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/comms-svc
      dockerfile: Dockerfile
    image: beedee/bee-comms:prod
    container_name: BeeComms
    hostname: bee-comms
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/comms.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [comms_data:/data]
    networks: [default]

  bee-exploration:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/exploration-svc
      dockerfile: Dockerfile
    image: beedee/bee-exploration:prod
    container_name: BeeExploration
    hostname: bee-exploration
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/exploration.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [exploration_data:/data]
    networks: [default]

  bee-safety:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/safety-svc
      dockerfile: Dockerfile
    image: beedee/bee-safety:prod
    container_name: BeeSafety
    hostname: bee-safety
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/safety.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [safety_data:/data]
    networks: [default]

  bee-notify:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:backend/services/notify-svc
      dockerfile: Dockerfile
    image: beedee/bee-notify:prod
    container_name: BeeNotify
    hostname: bee-notify
    environment:
      - PORT=8080
      - DATABASE_URL=file:/data/notify.db
      - SQLITE_PRAGMA_JOURNAL_MODE=wal
      - SQLITE_PRAGMA_BUSY_TIMEOUT=5000
      - SQLITE_PRAGMA_SYNCHRONOUS=normal
    volumes: [notify_data:/data]
    networks: [default]

volumes:
  profiles_data:
  results_data:
  comms_data:
  exploration_data:
  safety_data:
  notify_data: