version: '3.8'
services:
  bee-scraper:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-scraper
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: BeeScraper
    hostname: bee-scraper
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: scraperdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-gateway:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: BeeGateway
    hostname: bee-gateway
    environment:
      SCRAPER_SVC_URL: http://bee-scraper:80
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: bffdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
      - bee-scraper
      - bee-profiles
      - bee-results
      - bee-notify
      - bee-comms
      - bee-exploration
      - bee-safety
      - bee-rabbitmq
      - bee-redis


  bee-profiles:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-profiles
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    container_name: BeeProfiles
    hostname: bee-profiles
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: profilesdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-results:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-results
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    container_name: BeeResults
    hostname: bee-results
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: resultsdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-notify:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-notify
      dockerfile: Dockerfile
    ports:
      - "3004:80"
    container_name: BeeNotify
    hostname: bee-notify
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: notifydb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-comms:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-comms
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    container_name: BeeComms
    hostname: bee-comms
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: commsdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-exploration:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-exploration
      dockerfile: Dockerfile
    ports:
      - "3006:80"
    container_name: BeeExploration
    hostname: bee-exploration
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: explorationdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-safety:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:/services/bee-safety
      dockerfile: Dockerfile
    ports:
      - "3007:80"
    container_name: BeeSafety
    hostname: bee-safety
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: safetydb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-db:
    image: postgres:15
    container_name: BeeDb
    hostname: bee-db
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh
  bee-redis:
    image: redis:7
    container_name: BeeRedis
    hostname: bee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  bee-rabbitmq:
    image: rabbitmq:3-management
    container_name: BeeRabbitmq
    hostname: bee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
