version: '3.8'

services:
  # Sex Positions App with integrated scraper
  sex-positions-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - sex-positions-network

networks:
  sex-positions-network:
    driver: bridge
