version: '3.8'

services:
  # Just the main gateway service for testing
  beedee:
    build:
      context: https://github.com/Oasis256/BeeDee.git#main:services/beedee
      dockerfile: Dockerfile
    container_name: BeeGateway
    hostname: beedee
    ports:
      - "80:80"
    environment:
      - PORT=80
      - INTELLIGENCE_URL=http://bee-intelligence:8080
      - SOCIAL_URL=http://bee-social:4000
      - SCRAPER_URL=http://bee-scraper:3001
    networks:
      - bee-network
    restart: unless-stopped

  # Database for basic functionality
  bee-db:
    image: postgres:15-alpine
    container_name: BeeDatabase
    hostname: bee-db
    environment:
      - POSTGRES_DB=bee_main
      - POSTGRES_USER=beeuser
      - POSTGRES_PASSWORD=beepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bee-network

  # Redis for caching
  bee-redis:
    image: redis:7-alpine
    container_name: BeeRedis
    hostname: bee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bee-network

networks:
  bee-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
