version: '3.8'
services:
  bee-scraper:
    build: ./services/scraper-svc
    ports:
      - "3001:80"
    container_name: Bee-Scraper
    hostname: bee-scraper
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: scraperdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bff-gateway:
    build: ./services/bff-gateway
    ports:
      - "3000:80"
    container_name: Bff-Gateway
    hostname: bff-gateway
    environment:
      SCRAPER_SVC_URL: http://bee-scraper:80
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: bffdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-profiles:
    build: ./services/profiles-svc
    ports:
      - "3002:80"
    container_name: Bee-Profiles
    hostname: bee-profiles
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: profilesdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-results:
    build: ./services/results-svc
    ports:
      - "3003:80"
    container_name: Bee-Results
    hostname: bee-results
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: resultsdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-notify:
    build: ./services/notify-svc
    ports:
      - "3004:80"
    container_name: Bee-Notify
    hostname: bee-notify
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: notifydb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-comms:
    build: ./services/comms-svc
    ports:
      - "3005:80"
    container_name: Bee-Comms
    hostname: bee-comms
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: commsdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-exploration:
    build: ./services/exploration-svc
    ports:
      - "3006:80"
    container_name: Bee-Exploration
    hostname: bee-exploration
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: explorationdb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-safety:
    build: ./services/safety-svc
    ports:
      - "3007:80"
    container_name: Bee-Safety
    hostname: bee-safety
    environment:
      POSTGRES_HOST: bee-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: safetydb
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    depends_on:
      - bee-db
  bee-db:
    image: postgres:15
    container_name: Bee-Db
    hostname: bee-db
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: mainpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  bee-rabbitmq:
    image: rabbitmq:3-management
    container_name: Bee-Rabbitmq
    hostname: bee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
